### ISSUE TITLE
Each time I add/remove a field I loose it on the screen 

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#10]
Would it be possible to set the overflow of container of the `table_e_table_wrapper` always visible. This is not only a matter of setting the overflow-x to scroll, but also to set the height of the iframe large enough.

![newmips](https://user-images.githubusercontent.com/2980348/27072214-fed4f0ce-501f-11e7-9173-d8fc76ab60d4.png)

**Comment by newmips** [comment]
OK noted. For your information, we have component to manage timesheets which is available in last master release. Try instruction : `add component cra` and let me know... Documentation is incoming :-)

**Comment by alaindebecker** [comment]
Tu verrais mon Timesheet, Il est à tomber par terre.

Les besoins de Team-Partners étaient tellement divers, qu'il faut gérer des horaries de nuits, du travail en équipe, les 3 huit, les astreintes, les client dont l'horaire est de 45 heures par semaine, ceux qui sont ouvert le lundi à la place du samedi, les congés officiels différent par canton,... Je me suis tappé toute la législation suisse.
Et comme on avait besoin de données fiables, l'interface utilisateur est un user/password suivi d'un glissé de doigt sur l'écran pour la semaine...
