### ISSUE TITLE
Ciel qu'ais-je fais???

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#11]
J'étais en train de visualiser une entity, et j'ai entré la commande `delete entity <entity>`.

J'ai cru que je recevais ma feuille d'impôt.

![newmips](https://user-images.githubusercontent.com/2980348/27073213-5c2d78f6-5023-11e7-8a56-83134d68de3d.png)

**Comment by newmips** [comment]
Tu étais en train de consulter une page relative à l'entité que tu as essayé de supprimer.
Conclusion, quand il a rechargé l'URL, il n'a pas trouvé la page concernée.
Click sur le titre "cra-admin" pour revenir à la page d'accueil.

**Comment by alaindebecker** [comment]
Ca j'avais bien compris.

Mais serait-il possible d'enlever  404 **Erreur** 404 Erreur. 
A mon avis:
Le lien que vous avez suivi est incorrect ou la page peut avoir été suprimée. Vous pouvez retourner sur la page d'accueil ou revenir en arrière.
est un superbe message.

Pour paraphraser [Emile Wiska](http://www.writersua.com/articles/message/index.html), si l'utilisateur voit ce message, c'est que newmips l'a laissé tomber. Il faut le rassurer qu'il n'a rien cassé, et surtout ne pas en rajoutter à sa surprise. Par exemple, Java bani systématiquement le mot le mot Erreur, replacé par Exception. On a inventé des [Fail pets](http://uxmag.com/articles/the-evolution-of-fail-pets).

![newmips](https://user-images.githubusercontent.com/2980348/27085703-5d113b9a-5050-11e7-979c-5287f03b0187.png)

**Comment by newmips** [comment]
En phase. Chez nous le fail pet s'appelle Mipsy, c'est un petit robot ! Nous allons revoir le format de la page...

![bot-01_480](https://user-images.githubusercontent.com/8429204/27085933-fdbdbe42-5050-11e7-8102-499570291577.png)

**Comment by alaindebecker** [comment]
Oh mais qu'il est sympa ce petit Mipsy...
