### ISSUE TITLE
Retour à l'acccueil

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#12]
Un bouton équivalent à ` https://alaind.newmips.studio/default/home` serait bienvenu sur l'écran de prévisualisation.

S'il existe déjà, le rendre plus visible serait bienvenu aussi.

**Comment by newmips** [comment]
Le lien est un fil d'ariane en haut à droite : entre la progress bar du nombre d'instruction et le bouton déconnexion. Nous allons le remplacer par un bouton.

**Comment by alaindebecker** [comment]
Si vous parlez de celui-là, je ne l'avais simplement pas vu!
Ce n'est la peine de le remplacer par un bouton, il est très bien comme cela. Simplement rendez le un peu plus visible (taille).
Merci, 

![newmips](https://user-images.githubusercontent.com/2980348/27122249-6fdaa8de-50ea-11e7-94a2-8c15f84e9db5.png)

**Comment by alaindebecker** [comment]
Merci, Client pleinement satisfait
