### ISSUE TITLE
Question about field names (reopen)

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#14]
Reopen issue #8 (inadvertently closed by the administrator instead of the user).

But I have created a field called recovery_hash with the creation script.
How do I remove it or change its attribute ?

**Comment by annelvk** [comment]
To remove a field, you have to use the instruction "delete field FIELDNAME".
Use the instruction "list fields" to get the list of fieldnames and to be sure where the field has been created.
Then, use the instruction "select entity ENTITYNAME" before giving the instruction "delete field FIELDNAME".

Let us know if it solves your issue.

**Comment by alaindebecker** [comment]
It's a bit more complex.

The script (generated by program) used created field recovery_hash, which was written verbatim in the database.
 
When I issue the instruction `delete field recovery_hash`, newmips transforms it automatically in `delete field recovery hash`, which does not exists.

In my opinion, it is a real bug, in the script executor, which should apply the same rule as the command executor, and replace _unterbars_ with spaces.

**Comment by alaindebecker** [comment]
Ok. I smell that one will never be solved.

**Comment by alaindebecker** [comment]
Ok. I smell that one will never be solved.

**Comment by alaindebecker** [comment]
Ok. I smell that one will never be solved.
