### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#15]
In the designer, we have to setup 3 different pages per entity, for creation, update, and show.

Wouldn't it possible to have 1 page plus 3 variants? 
Or one show page, plus one create/update page, plus one create page ?

**Comment by newmips** [comment]
For the moment, we prefer to keep the possibility to design each page independantly.

**Comment by alaindebecker** [comment]
Il est étrange qu'une feature request puisse être fermée...

De la même façon, en fait, qu'il est étrange qu'un autre que l'auteur ferme lune demande.

Sur le bug tracking de github, qui ne permet pas à un utilisateur de réouvrir une issue fermée par un administrateur, on pourrait s'attendre à ce ce soit le demandeur lui-même qui décide de savoir si une demande est ouverte ou non.

J'aurais reçu un message me demandant de fermer une demande ouverte depuis une semaine, j'aurais compris. Mais là, je suis en train de me demander ce que j'ai fais pour qu'un moderateur me demande de changer de sujet de conversation ?

![newmips](https://user-images.githubusercontent.com/2980348/27121318-1a6c42ac-50e7-11e7-8376-587fea5f0213.png)

**Comment by newmips** [comment]
Joker :-)

**Comment by alaindebecker** [comment]
No offence. Honest.

Nevertheless mention to your decision maker that github bug tracking is really lacking of a way to distinguish between emergency alarms and "nice to have" wishes.
I try stackoverflow.
