### ISSUE TITLE
Question: script mode for the designer

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#16]
It there a script mode for the designer?

The question comes from the fact that putting a good layout require a lot of back and forth with the Preview screen and, in my case where there are a lot of fields, sometimes to rerun the whole creation script.

In that case I also have to redo the layout, 3 times per entity, by hand. It would be better if this could be stored in a text file somewhere.

**Comment by newmips** [comment]
We have already been thinking on setting instructions to manage a Bootstrap structure in the page:
`add row`
`add column`
Etc.
But, there is no script mode for the designer for the moment.

When using the designer, modified files are directly available in source code of application. Check following files:
`views/e_myentity/create_fields.dust`
`views/e_myentity/show_fields.dust`
`views/e_myentity/update_fields.dust`
`views/e_myentity/list_fields.dust`

**Comment by alaindebecker** [comment]
Ahhh! Ok! I see: Next release. That's life...

Nevertheless, the workaround with a direct editing was appreciated to the full.

![newmips](https://user-images.githubusercontent.com/2980348/27123193-686fe232-50ed-11e7-9487-edca4c0f23f8.png)

**Comment by alaindebecker** [comment]
Closed. Very complete answer
