### ISSUE TITLE
Mot de passe oublié

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#18]
Sur le site newmips.com, au login, il manque un bouton "J'ai oublié mon mot de passe".
 [En fait je me souviens du mot de passe, je n'ai pas besoin d'un nouveau, C'est pour vous signaler que,.. Enfin, je me comprend. J'espère que vous aussi...]
 
![newmips01](https://user-images.githubusercontent.com/2980348/27475204-98b46170-5804-11e7-9c14-13beaab6612c.png)

**Comment by Syno0** [comment]
Bonjour, 
en effet cette option indispensable vient d'être ajoutée sur notre site web.
Merci pour ce retour.
