### ISSUE TITLE
Important: Broken link on User Home page

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#19]
According to #7 it it https://**alaind**.newmips.studio.

It would be nice to also have the list of https://mycompany-**myapps**.newmips.studio, as well as the list of https://mycompany-myapp.newmips.cloud/.

![newmips02](https://user-images.githubusercontent.com/2980348/27475351-38e9de54-5805-11e7-8aa7-4051ba589547.png)

**Comment by Syno0** [comment]
Hi,
we've just fix this issue in the last website update.
Thanks for helping.
