### ISSUE TITLE
How to rename entity?

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#2]
J'ai créé une entité "Customers". Comment la renommer en "Customer"?

**Comment by newmips** [comment]
Tu la supprimes, et tu la recréées. La création et la suppression sont rapides à faire.
Cela étant, si tu as déjà créé beaucoup d'éléments, tu as la possibilité :
1. De changer les traductions dans les fichiers du répertoire "locales"
2. De modifier le nom de l'entité dans le répertoire "Models" et en base (cette seconde pratique est **fortement déconseillée** dans la mesure où on touche au moteur du système)

**Comment by alaindebecker** [comment]
La solution 1 est un coup de génie.

Pour la solution 2, je n'ai pas trouvé le répertoire "Models".

**Comment by newmips** [comment]
Le répertoire "Models" est masqué dans la version en ligne afin d'éviter les mauvaises pratiques de ce genre ^^
