### ISSUE TITLE
Bug in newMips installation 

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#20]
I have just installed a newMips by downloading the zip from github.
I have recreated the mySql and launched start-newmips.bat
I can log on 127.0.0.1:1337

But I am unable to select/create a project. 
The log says:

```
events.js:160
	throw er; // Unhandeled 'error' events

Error: ENOENT: no such file or directory, open 'C:\nodejs\newmips-master\workspace\1\model\e_user.js'
    at Error(native)
```

**Comment by newmips** [comment]
Hi, have you resolved this issue ? In the meanwhile, we will check if last deliveries are clean...

**Comment by alaindebecker** [comment]
No, that one is a really hard one.

I screwed up my newMips when my batteries went flat while Mipsette was in
the process of creating a new app. After that, she was lost in her
indexing prefixes: 4_e_entity instead of 3_e_entities, and similar...

I deleted the newMips folder, reinstalled a fresh downloaded, droped and
rebuild the database.

But it seams that some files in the workspace (or maybe a reference to
them) are kept in some hidden or tmp directory. [*which is a good thing in
other circumstances*].

In my opinion, the problem is not in your distribution, but rather in some
place on my file system.

I cannot test it right now, since my machine is at home.

Kind regards,
AlainD

**Comment by annelvk** [comment]
Usually this kind of error occurs when you do not have write access onto the directory "workspace" or when it does not exist. 

Let us know later if you find a solution.

Best regards,
AnneLVK

**Comment by alaindebecker** [comment]
Nope, it's deeper that that.
The C:\nodejs\newmips-master\workspace directory exists, but newMips insists in finding 
C:\nodejs\newmips-master\workspace\1\model\e_user.js.

There is one user (admin) in the mysql user table, but no json was created.

**Comment by alaindebecker** [comment]
Woks now
