### ISSUE TITLE
Very serious and critical BUG in api

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#25]
The api/getToken does not work.
The http://127.0.01:9034 does not listen at all. 

The correct api url is http://127.0.0.1:9003.
**Please correct**

_Documentation is like sex: when it is good, it is very, very good; and when it is bad, it is better than nothing._   -- Dick Brandon

**Comment by newmips** [comment]
On localhost, port of generated application depends on the ID of your application in the database. If your application has ID 6 for instance, you can access it on port 9006. ID number is also available in session data and displayed on preview screen.

**Comment by alaindebecker** [comment]
That's fine for the code. I was talking about the **documentation**. 

To get the real port, I am able to netstat. However, newMips is marketed as a "low-code" product.

Additionally, around the port 900*, I already have a set of HSQL database and PDI-carte server. It would be easier for me to change the newMips port rather than reconfigure these ports on each of my computers.
