### ISSUE TITLE
Issue in script mode

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#26]
When creating a entity in script mode newMips converts its name in **entity.e_<name>.label_entity**, which rises a lot of problem afterwards.
Same thing for modules and fields.

Reproduce.:
1. Manually create project Classic Models
2. Manually create application Classic Models
3. Manually create module Administration
4. Execute the following script
```
select project classicmodels
select application Classic Models
select module Administration
create entity Job Title
  add field job title
create entity order status
  add field order status
```
5. The following entities are created 
    **entity.e_job_title.label_entity**
    **entity.e_order_status.label_entity**
6. Nothing can be done with these

**Comment by newmips** [comment]
Hi,
We have not acheived to reproduce this issue in version 2.4.
Tell us if you need to upgrade.

**Comment by alaindebecker** [comment]
Correct this happens from time to time, randomly.
