### ISSUE TITLE
Horizontal bars in subentities not showing

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#27]
In a tab for a subentities the horizontal bar does not show. As a consequence, it is impossible to modify or delete it.

![image](https://user-images.githubusercontent.com/2980348/33882845-d7f555a8-df39-11e7-9fab-5a06b0b9660e.png)

**Comment by Syno0** [comment]
Hi, thanks for the feedback, it'll be fixed in the next release.
https://github.com/newmips/newmips/commit/b299e2393cff5df95e15bc189dcd8b9ea164c579

**Comment by alaindebecker** [comment]
That's good news. Thanks Syno.
