### ISSUE TITLE
Change color for Success of First connection

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#28]
![newmips](https://user-images.githubusercontent.com/2980348/34053377-e50495e4-e1c6-11e7-865d-5901ecb57e60.png)

**Comment by newmips** [comment]
Hi,
In the beginning, color was green, but users thought they were automatically logged in.
So we have set color to orange, in order users to pay attention to what they were doing.
++

**Comment by alaindebecker** [comment]
And they are not logged-in automatically ?
++
AlainD
