### ISSUE TITLE
default value do not accept dots

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#29]
I need to issue the following command:
`add field Badge Number with default value 756.2904.2452.20`

But Mipsy just erases all my dots.

**Comment by Syno0** [comment]
Hi, indeed Mipsy is today a little strict concerning the instruction input in the preview, we will remove these restrictions and rather do server side checks to avoid this kind of problem.

**Comment by alaindebecker** [comment]
Thanks,
