### ISSUE TITLE
How to rename IDs

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#3]
En créant l'entité "customers",  le sytème a créé le champ "IDCustomers".
Comment spécifier que la clé s'appèle "CustomerNumber" ?

**Comment by newmips** [comment]
2 solutions :
1. Tu modifies le fichier des traductions "locales" pour afficher "CustomerNumber" au lieu de "IDCustomer"
2. Tu créés un second champ "CustomerNumber" que tu masques dans le formulaire de création mais que tu initialises avec l'ID dans le POST de création. Ensuite, il va se comporter comme un champ indépendant.

**Comment by alaindebecker** [comment]
Merci, mais ce n'est pas forcément une bonne idée de renommer le champ IDcustomers.

En effet, c'est la clé de la table de donnée 1_e_customers qui est lentement variable (surrogate key). L'identifiant dans cette table n'est plus customerNumber, mais customerName+version.
D'ailleurs le champ IDcustomers n'apparait pas sur le formulaire de saisie des données.

Cela dit les solutions restent valables pour les autes champs comme customerName,...
