### ISSUE TITLE
Menu logout not visible enough

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#32]
Le dropdown-menu du header à droite, avec les boutons « Paramètres » et « Se déconnecter » ne se voit pas très bien et se confond parfois avec l’écran principal. Mettre le fond du `.navbar-nav > .user-menu > .dropdown-menu > .user-footer` dans la même couleur que celle du `.main-header li.user-header`.

A passage, mettre une ombre autour du dropdown-menu.

**Comment by newmips** [comment]
Nous allons voir ce qu'il est possible d'améliorer.
La prochaine version 2.5 qui sort à la fin du mois va permettre de gérer des thèmes.
La question ne se posera plus.

**Comment by alaindebecker** [comment]
Deux bonne nouvelles à la fois. C'est super.

Cela dit, il serait tout demême sympa de mettre une ombre par défaut.
Parce que je connais deux types d'utilisateurs: ceux qui ont peur de gérer les thèmes eux-mêmes, et ceux qui sont trop flemme pour le faire.
