### ISSUE TITLE
How to have a referred-to field depend on the user ? 

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#34]
I have an entity `Customer `with a field `SalesRep` referring to an external entity `Employee`. Naturally, the `SalesRep` depends on the login user.

How to?

**Comment by newmips** [comment]
1. Make a link between employee and user
```
select entity employee
add field SalesRep related to user using login
```

2. In Customer route, execute a promise to select employee ID for current user ; something like...

  ```
  var promises = [];

    promises.push(new Promise(function(resolve, reject){
	var query = "SELECT id AS employee_id"
			+ " FROM 1_e_employee"
			+ " WHERE fk_id_user_employee=" + req.session.passport.user.id;
	models.sequelize.query(query, {type: models.sequelize.QueryTypes.SELECT}).then(function (result) {
		if(result[0].employee_id === null) employee_id = "";
		resolve({employee_id: result});
	});
}));

    Promise.all(promises).then(function (results) {
	for (var i = 0; i < results.length; i++)
		for (var prop in results[i])
			data[prop] = results[i][prop];

	data.toastr = req.session.toastr;
	req.session.toastr = [];
	res.render('e_employee/create_form', data);
});
```


3. Send data to page and set value of SalesRep with ID you have retrieved
`<input name="f_salesrep" value="{employee_id}" />`

**Comment by alaindebecker** [comment]
Ok, Let me ask the question with a different wording:

I have an entity `Assuance` with a field `Contact` referring to an other entity. Naturally, the `Contact` depends on the login user.

How much would it cost to teach Mipsy to write the code mentioned in the part 2 of your solution ?

Naturally, this cost will probably include the analysis and public discussion required to make the solution sufficiently generic to be worth to include in the OpenSource code.
