### ISSUE TITLE
How to jump to the mother entity of a sub-entity 

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#36]
I have an entity Employee which is also a tab (sub entity) of the entity Office. The `Office` has been created before the `Employee`, so it is possible to list all the `Employee `by clicking on the left panel. 

Is it then possible to have a click or a button so that I jump to the corresponding `Office` ?

For example, if I click on Dianne Murphy, I jump to the San Fransisco office, and if I click on William Paterson, I jump to Sidney office.

It would be nice if the solution could avoid crawling in the dust.

**Comment by newmips** [comment]
There is no automatic feature like this. You should add a button in Employee page that redirects to Office page. Something like :
    <a class="btn btn-info" href="/office/show?id={fk_id_office_office}">...</a>

**Comment by alaindebecker** [comment]
Not a solution
