### ISSUE TITLE
Undo on the studio

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#39]
As far as I understand, there is no undo/redo functionality in the Studio, even with a clever use of save+reload.  You need to go into the github repository, with a high risk of messing everything up. 

It would be nice to have an undo (or a rollback, or unsave, or revert) instruction that restore the local session at the previous save point.

The use case goes as follow:
a) The user makes a save
b) The user makes some modification
c) The user discovers his/her modifications are wrong
d) The user issue the undo
e) The Studio and the local machine goes to the lase savepoint (= a)

To have more fancy stuff, you may think about multiple savepoints, then a redo, then an automatic save after each command.

**Comment by newmips** [comment]
In my opinion, "Undo" feature should be implemented in the studio to rollback last instruction to the bot. Not to rollback on source repo.

**Comment by alaindebecker** [comment]
Not really. What matters (for the customer) is the source repo. The studio is there for the dev.
