### ISSUE TITLE
Command line to define new entity (data row)

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#4]
Existe-t-il une commande equivalente à INSERT INTO entity VALUES ?

**Comment by newmips** [comment]
Il n'existe pas d'instruction pour intégrer des données via l'automate. Par contre, il est possible d'utiliser la fonction d'import présente sur la page d'accueil (bouton "Import").

1. Choisir l'application de son choix dans la liste déroulante
2. Indiquer le fichier de configuration au format JSON à charger (ex : 01 - config-import-mon-entite.txt)
3. Indiquer le fichier des données au format Excel ou CSV (ex : 01 - mon-entite.xslx)

Dans l'exemple joint, l'entité a deux champs : "name" et "code" (le fichier des données a deux colonnes "nom" et "code").

[01 - config-import-mon-entite.txt](https://github.com/newmips/newmips/files/1065678/01.-.config-import-mon-entite.txt)
[01 - mon-entite.xlsx](https://github.com/newmips/newmips/files/1065679/01.-.mon-entite.xlsx)
