### ISSUE TITLE
Default language

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#44]
During the development, I need to check the English version as well as the French version.

I did not found a way to do it on the top left menu (nearby the `user/disconnect` button), and changing my default browser language did do anything.

I tried to change the `workspace/{app}/config/language.json` with no effect.

Is there any known way to do it?

**Comment by Syno0** [comment]
Hi, the application language is linked to your user account. That mean if you want to change your language in the application you have to go in your account settings and click on the language you want.

![image](https://user-images.githubusercontent.com/14804727/38570574-77ce101c-3cee-11e8-94c8-9ceb9e44e0ba.png)

![image](https://user-images.githubusercontent.com/14804727/38570586-83304664-3cee-11e8-965e-46bdd5b096aa.png)

**Comment by alaindebecker** [comment]
C'est parfait.
