### ISSUE TITLE
installation : Port mysql

### ISSUE THREAD

**Issue by roxane451** [newmips/newmips#45]
Bonjour Mipsy,
J'essaie d'installer newMips sur ma machine, mais mon MySql utilise le port 8889, parce que il a été installé par MAMP.
Du coup "mysql -u newmips -pnewmips newmips" me répond "Access denied for user newmips@localhost". 
Pour info, je suis sur un Mac.
Roxane

**Comment by EoiFirst** [comment]
Bonjour Roxane,
Tu trouveras dans le fichier `/config/database.js` la possibilité de définir le port de ton application.

Cependant l'erreur n'a pas l'air de venir du port mais plutôt de l'utilisateur mysql.
Tu trouveras dans ce même fichier les configurations pour définir ton utilisateur comme il est défini dans ta BDD mysql.

NB: Le fichier `/config/database.js` est également disponible dans `structure/template/config/database.js`. Celui-ci défini la configuration des applications générées, alors que le premier concerne le générateur

Jérôme

**Comment by roxane451** [comment]
Merci beaucoup Jérome, ça fonctionne !

Roxane

**Comment by roxane451** [comment]
Désolé ça ne fonctionne pas si bien que ça....

```
App Log: ERROR - SYNC

App Log: { SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at Handshake._callback (/Users/roxanequatrecentcinquanteetun/Downloads/newmips-master/workspace/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:79:20)
    at Handshake.Sequence.end (/Users/roxanequatrecentcinquanteetun/Downloads/newmips-master/workspace/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Protocol.handleNetworkError (/Users/roxanequatrecentcinquanteetun/Downloads/newmips-master/workspace/node_modules/mysql/lib/protocol/Protocol.js:364:14)
```

**Comment by EoiFirst** [comment]
Du coup c'est le problème dont tu parlais dans ton premier message, mauvais port :)
`connect ECONNREFUSED 127.0.0.1:3306` 3306 doit donc être reconfiguré dans `database.js`

**Comment by roxane451** [comment]
A l'install:
```
./install.sh/ line 47: mysql: Command not found
./install.sh/ line 48: mysql: Command not found
```

Après creation et remplissage de la base avec les commandes sql à la main, et changement de la config à la main, on est parti.

**Comment by Syno0** [comment]
Bonjour Roxane,
on n'a pas encore totalement gérer l'installation simplifiée sur MAC.
Pour le moment il faudrait que tu executes à la main ce que le fichier install.sh est sensé faire.

Pour cela il te faut dans un premier temps executer ces lignes à la racine du générateur:
```
npm install
cp structure/template/package.json workspace/
cd workspace
npm install
```

Ensuite il faut préparer la base de données, et pour cela tu as tous les fichiers nécessaires dans /sql. Il te suffit d'executer les fichiers dans l'ordre (00, 01, 02). Si tu vois le fichier 04-session-for-postgres.sql celui là ne l'executes pas, c'est pour postgres et non MySQL.

Enfin tu n'as plus qu'à faire ```node server.js``` et si la config/database.js et la structure/template/config/database.js est ok  (bon user, bon password, bonne database et bon port) le processus node devrait se lancer correctement.

**Comment by roxane451** [comment]
Merci, tout est OK.

**Comment by roxane451** [comment]
Ca à marcher une fois puis il me lance sur 3306 malgré que le fichier de config mentionne 8889.

[newmips.log](https://github.com/newmips/newmips/files/2375749/newmips.log)

[database.js](https://github.com/newmips/newmips/files/2375761/database.txt)

**Comment by Syno0** [comment]
Le problème a-t-il été résolu ?

**Comment by roxane451** [comment]
Tout est ok, merci beaucoup
