### ISSUE TITLE
Linux centric (=non windows) command in last release 

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#46]
With a fresh install, I get the following error:
```
{ Error: Command failed: cp C:\newmips2.6\structure/../structure/template/package.json C:\newmips2.6\structure/../workspace/
'cp' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cp C:\\newmips2.6\\structure/../structure/template/package.json C:\\newmips2.6\\structure/../workspace/' }
events.js:160
      throw er; // Unhandled 'error' event
      ^
```

**Suggested diagnostic:**
This can come from `modules_handle.js:14` or from `structure\structure_application.js:62`.

**Suggested correction:**
Use `process.platform` to chek if you on a windows OS and, in this case use

- in `modules_handle.js:14`
    `cmd = 'xcopy /e structure/template/node_modules workspace/'`;
    See [here](https://support.microsoft.com/en-us/help/323007/how-to-copy-a-folder-to-another-folder-and-retain-its-permissions) if you need to copy hidden files and/or privileges.

- in `structure\structure_application.js:62`:
     `var cmd = 'copy ' + dir + '/../structure/template/package.json ' + dir + '/../workspace/';`

**Comment by alaindebecker** [comment]
It doesn't work.  It is also  needed to change `/` in `\` (that is `\\`).

**Comment by Syno0** [comment]
I was currently working and testing it before answering you, that's why the first commit did not work.

You can try again, it should work now: https://github.com/newmips/newmips/commit/53f8db321d3b5649209f4081357a2614cb8e2369

**Comment by alaindebecker** [comment]
Pas de soucis. Et mille mercis.

J'ai un agenda chargé cet après-midi.
Et puis il faut aussi que je resynchronise une prod avec son studio
fraichement migré...

J'ai peur de ne pas pouvoir tester avant 17:00.
A demain, donc...
AlainD

**Comment by alaindebecker** [comment]
Comme c'est beau l'informatique quand ça marche !

[image: image.png]
