### ISSUE TITLE
Défaut dans la sécurité

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#48]

**Comment by Syno0** [comment]
Description maybe ?

**Comment by alaindebecker** [comment]
Le bouton paramètre du menu déroulant de l’utilisateur en haut à gauche, permet à l’utilisateur de voir son profil : langue, identifiant email, roles, groupes. C’est bien. 

**Mais il devrait pas pouvoir modifier son rôle et son groupe.**

**Comment by Syno0** [comment]
Cela a déjà été pris en compte dans la version 2.7 qui sort très prochainement !

**Comment by alaindebecker** [comment]
Parfait. Merci.

**Comment by alaindebecker** [comment]
Parfait. Merci.
