### ISSUE TITLE
BUG: champ "phone" restiruées en type "number"  

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#5]
J'ai créé un champ téléphone, avec `create field DateOfBirth with type date`.

Mais sur l'écran de saisie il est restitué comme ` <input class="form-control input" placeholder="phone" name="f_phone" value="" type="number">`.

**Comment by newmips** [comment]
Je comprends que l'instruction passée est : create entity Phone with type phone
En phase ?

**Comment by newmips** [comment]
Par défaut, le champ est de type "number"... Nous allons le passer en type "string".
Il est toutefois possible d'appliquer un format de téléphone en enlevant les commentaires des lignes 108 et 109 du fichier "public/js/newmips.js" :
`    /* Uncomment if you want to apply a mask on tel input */
    /*$("input[type='tel']").inputmask({mask: "+## # ## ## ## ##"});*/`

**Comment by alaindebecker** [comment]
Il existe un <input type=tel"> pour ce type de champs.

D'après http://caniuse.com/#feat=input-email-tel-url, il semble être
supporté par touts les browsers en dernière version.

Les browsers qui ne le supportent pas le covertissent silencieusement en
type "String".

**Comment by alaindebecker** [comment]
Oui, " create entity Phone with type phone".

J'aurai peut-être du dire "create entity Phone with type tel".

A ma décharge, je n'avais pas la documentation html5 sous les yeux.

AlainD

**Comment by alaindebecker** [comment]
Le bug était entre la chaise et l'écran.
