### ISSUE TITLE
Problem loading data.

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#6]
Bonjour,

newmips m'a préparé une démo. 

Les scripts de création ont parfaitement fonctionnés, mais impossible de charger les données. 
D'après le log, les scripts essayent de charger les tables 2_e_duty_station
```
REQUEST:  INSERT INTO 2_e_duty_station (`f_name`, `f_code`) VALUES('Milan', 'MIL');
ERROR:  ER_NO_SUCH_TABLE: Table 'newmips.2_e_duty_station' doesn't exist 
```
Alors que dans msyql la table s'appele 3-e-duty-station.

-----------------------------------
J'ai essayé de renomer la table 3-e-duty_station en 2-e-duty-station, mais alors newmips me répond
```
REQUEST:  INSERT INTO 1_e_duty_station (`f_name`, `f_code`) VALUES('Milan', 'MIL');
ERROR:  ER_NO_SUCH_TABLE: Table 'newmips.1_e_duty_station' doesn't exist
```
-----------------------------------
Logique, mais pas d'un grand secours !

**Comment by newmips** [comment]
Bonsoir,
A la lecture de l'erreur, je pense que ce n'est pas la bonne application cible qui a été choisie. 
Dans le menu d'import des données, il y a 3 zones à remplir :
1. L'application cible
2. Le fichier JSON de configuration
3. Le fichier Excel ou CSV de données.
C'est la valeur dans la première liste déroulante qui n'a pas été correctement choisie.

Le plus simple (maintenant que le nom des table a été changé :-( ) est de revenir à la page d'accueil, lister les applications disponibles, supprimer le projet en question et recommencer le chargement du script.

Ensuite, il faut aller dans l'import de données, choisir la nouvelle application créée, le fichier JSON et le fichier Excel / CSV. Puis revenir à l'accueil (pour recharger la page) et recommencer pour chaque couple de fichiers.
