### ISSUE TITLE
What is my app url?

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#7]
Bonjour,
Je viens de créer une application et on m'indique que 
`L'url de votre application sera: cra-admin
`
ce qui me semble un peu court.
D'habitude, on m'indique un url du genre `https://cra-admin.newmips.je-ne-me-rappèle-plus-très-bien.com`.

A ce sujet, serait-il possible d'avoir cet url sur un bouton où mieux, systématiquement, sur l'écran d'acceuil.

**Comment by newmips** [comment]
Bonjour,
Il y a deux partie dans la solution Newmips en ligne : une partie Studio (espace de création d'applications) et une partie Cloud (hébergement de l'application utilisateur)

Pour un compte "myCompany" et une application "myApp", l'URL d'accès au Studio sera :
https://mycompany.newmips.studio/

L'application créée sera lancée en prévisualisation sur :
https://mycompany-myapp.newmips.studio/ 

Dès lors que l'application est déployée (instruction "deploy") elle sera disponible sur :
https://mycompany-myapp.newmips.cloud/

Pour une utilisation en local, il n'y a pas de déploiement en tant que tel (pas d'environnement pour héberger la production client). Pour autant, la commande deploy donnera l'URL : `http://127.0.0.1:9023/` avec 23 l'identifiant de l'application créée.

**Comment by alaindebecker** [comment]
Oui, d'accord...

Mais serait-il tout de même possible d'avoir cet url sur un bouton où mieux, systématiquement, sur l'écran d'acceuil ?

Pas forcément aujourd'hui, mais dans une prochaine release?

**Comment by newmips** [comment]
Euh... pas sûr de bien comprendre. 
Ce que tu veux c'est voir l'application "en grand" (hors iframe) dans un onglet de ton navigateur ?

**Comment by alaindebecker** [comment]
Ce que je veux, c'est améliorer la lisibilité pour le débutant que je suis.
Peut-être:

![newmips](https://user-images.githubusercontent.com/2980348/27120539-48f9ef82-50e4-11e7-9f27-c2372bcf8751.png)
