### ISSUE TITLE
Question about field names

### ISSUE THREAD

**Issue by alaindebecker** [newmips/newmips#8]
Underlines are removed from the command box: `create field date_from` --> create field datefrom.

Normal?

**Comment by newmips** [comment]
Yes. It's normal. Initially, instructions are given by voice...
If you need to have a field with an underscore, just leave a blank :
`create field date from`

**Comment by alaindebecker** [comment]
But I have created a field called recovery_hash with the creation script.
How do I remove it or change its attribute ?
